name: Test Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
      
    - name: Install proxyquire for tests
      run: npm install --save-dev proxyquire
    
    - name: Build extension
      run: npm run build
    
    - name: Run standard tests
      run: npm run test-unit
    
    - name: Run coverage tests
      run: npm run coverage-test
    
    - name: Generate coverage report
      run: npm run coverage
    
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      # Only run if the token is available (for PRs from forks)
      if: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository }}
      with:
        # Make token optional for public repos
        token: ${{ secrets.CODECOV_TOKEN || '' }}
        file: ./coverage.lcov
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
